apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bmuo13j2v-python 
  janus-idp.io/tekton: bmuo13j2v-python
  backstage.io/kubernetes-id: bmuo13j2v-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bmuo13j2v-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml