apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bmuo13j2v-python-gitops
  description: This is GitOps manifest for bmuo13j2v-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bmuo13j2v-python
    backstage.io/kubernetes-id: bmuo13j2v-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bmuo13j2v-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bmuo13j2v-python
